version: "3.8"
services:
  db:
    image: postgres:16
    container_name: db
    command: -p 5454
    env_file:
      - .env-non-dev
    volumes:
      - data-volume:/var/lib/postgresql/data

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 80:8000
    depends_on:
      - db

volumes:
  data-volume: